apiVersion: apps/v1
kind: Deployment
metadata: 
  name: app2
  labels:
    name: app2
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      name: app2
      tier: frontend
  template:
    metadata:
      labels:
        name: app2
        tier: frontend
    spec:
      containers:
      - name: app2
        image: mlndockerhub/app2:v1
        