apiVersion: apps/v1
kind: Deployment
metadata: 
  name: app2
  labels:
    name: app2
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      name: app2
      tier: frontend
  template:
    metadata:
      labels:
        name: app2
        tier: frontend
    spec:
      containers:
      - name: app2
        image: mlndockerhub/app2:v1
        
---
apiVersion: v1 
kind: Service
metadata:
  name: app2
spec:
  selector:
    name: app2
    tier: frontend
  ports:
  - name: nginx-svc-port
    protocol: "TCP"
    port: 80
    targetPort: 80
    